config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :prospects do
    resources :conversations
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :prospect

  validates :content, presence: true
end

app/models/prospect.rb
class Prospect < ApplicationRecord
  has_many :conversations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def new
    @prospect = Prospect.find(params[:prospect_id])
    @conversation = Conversation.new
  end

  def create
    @conversation = Conversation.new(conversation_params)
    @prospect = Prospect.find(params[:prospect_id])
    @conversation.prospect = @prospect
    if @conversation.save
      redirect_to prospect_path(@prospect)
    else
      render :new
    end
  end

  def destroy
    @conversation = Conversation.find(params[:id])
    @conversation.destroy
    redirect_to prospect_path(@conversation.prospect)
  end

  def update
    if @conversation.update(conversation_params)
      redirect_to ...
    else
      render :edit
    end
  end

  private

  def conversation_params
    params.require(:conversation).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    user_signed_in? ? redirect_to(prospects_path) : redirect_to(new_user_session_path)
  end
end

app/controllers/prospects_controller.rb
class ProspectsController < ApplicationController

  def index
    @prospects = Prospect.all
  end

  def new
    @prospect = Prospect.new
  end

  def create
    @prospect = Prospect.new(prospect_params)
    if @prospect.save
      redirect_to new_prospect_path
    else
      render :new
    end
  end

  def show
    @prospects = Prospect.all
  end

  def update
    find_prospect
    @prospect.update(prospect_params)
    redirect_to prospect_path(@prospect)
  end

  def edit
    @prospect = Prospect.find(params[:id])
  end

  def destroy
    @prospect.destroy
    redirect_to prospects_path
  end

  private

  def set_prospect
    @prospect = Prospect.find(params[:id])
  end

  def prospect_params
    params.require(:prospect).permit(:name, :last_name, :phone, :email, :status)
  end

  def find_prospect
    @prospect = Prospect.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/conversations/new.html.erb
<%= simple_form_for [ @prospect, @conversation ] do |f| %>
  <%= f.input :content %>
  <%= f.submit "Cargar conversación", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CRM</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/prospects/_form.html.erb
<%= simple_form_for(@prospect) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :last_name %>
    <%= f.input :phone %>
    <%= f.input :email %>
    <%= f.input :status, as: :collection_select, collection: [['prospect', 'prospect'], ['interesting', 'interesting'], ['client', 'client']] %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %> 
  </div>
<% end %>

app/views/prospects/edit.html.erb
<h1>Editar Prospecto</h1>

<%= render 'form', prospect: @prospect %>

<%= link_to 'Mostrar', @prospect %> |
<%= link_to 'Atras', prospects_path %>

app/views/prospects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Prospectos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellidos</th>
      <th>Telefono</th>
      <th>Email</th>
      <th>Estado</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @prospects.each do |prospect| %>
      <tr>
        <td><%= prospect.name %></td>
        <td><%= prospect.last_name %></td>
        <td><%= prospect.phone %></td>
        <td><%= prospect.email %></td>
        <td><%= prospect.status %></td>
        <td><%= link_to 'Show', prospect %></td>
        <td><%= link_to 'Edit', edit_prospect_path(prospect) %></td>
        <td><%= link_to 'Destroy', prospect, method: :delete, data: { confirm: '¿Estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'Nuevo Prospecto', new_prospect_path %>

app/views/prospects/new.html.erb
<h1>Nuevo Prospecto</h1>

<%= render 'form', prospect: @prospect %>

<%= link_to 'Back', prospects_path %>

app/views/prospects/show.html.erb
<p id="notice"><%= notice %></p>

<% @prospects.each do |prospect|%>

<p>
  <strong>Nombre:</strong>
  <%= prospect.name %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= prospect.last_name %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= prospect.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= prospect.email %>
</p>

<p>
  <strong>Estado:</strong>
  <%= prospect.status %>
</p>
<% end %>





<%= link_to 'Back', prospects_path %> |

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "https://w7.pngwing.com/pngs/483/552/png-transparent-software-testing-logo-management-computer-software-company-black-font.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Prospectos", "#", class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Iniciar sesión", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>